[target.xtensa-esp32-none-elf] # esp32
runner = "xtensa-esp32-elf-gdb -q -x openocd.gdb"
rustflags = [
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",
]

[build]
target = "xtensa-esp32-none-elf"
rustc = "/home/grey/development/cryptok/rust-xtensa/build/x86_64-unknown-linux-gnu/stage2/bin/rustc"
rustdoc = "/home/grey/development/cryptok/rust-xtensa/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc"

[unstable]
build-std = ["core"]
